Metehan1 = "Ne kadar değersiz olursa olsun toprak devletin temelidir; hiç kimseye verilemez."
Metehan2 = "Benden eğerimi isteyin vereyim, çadırımı isteyin vereyim, atımı isteyin vereyim fakat vatanımdan hiç kimse bir karış toprak istemesin vermem, veremem."
Metehan3 = "Eğer Çin hükümdarı, Hunluların Çin sınırlarına yaklaşmasını istemiyorsa, sınır muhafızlarına ve sınır boyunda yaşayan halka sınırlardan uzaklaşmayı emretmelidir."
Metehan4 = "Bataklıkta doğmuş, atlar ve öküzler arasında kırda büyümüş kimsesiz ve yıpranmış imparatoriçe! Çin'de gezmek için birkaç defa sınırınıza gelmiştim. Kimsesiz ve yıpranmış imparatoriçe taht üzerinde yalnızdır. Her iki padişah can sıkıntısı içinde. Bende olmayanı bende olanla değiştirmek istiyoruz."
Metehan5 = "Hun, göğün mağrur oğludur ki ufak saray teşrifatı ve merasimine ehemmiyet vermez."
Metehan6 = "Göğün inaneyetiyle askerlerimiz sağlam, atlar güçlü oldular. Yüençiler yendiler. Kılıçtan geçirip veya itaate alıp Leu-lan, Usun, Huse ve diğer yirmi altı ülkede karar kıldılar. Bu ülkelerin ahalisi Hun ordusu arasına geçip bir aile oldular."
Metehan7 = "İsterse üzerinde ot bitmesin ne kadar değersiz olursa olsun, toprak devletin temelidir ve hiç kimseye verilmez."
